# MQTT TLS Certificate Generation Script
# Generates self-signed CA + server certificates for Mosquitto TLS
# Output: ../certs/ (relative to this script)
# Also copies to D:\tools\mosquitto\certs\ if native Mosquitto is detected

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$DockerCertsDir = $ScriptDir
$NativeCertsDir = "D:\tools\mosquitto\certs"

# Check if OpenSSL is available
$openssl = Get-Command openssl -ErrorAction SilentlyContinue
if (-not $openssl) {
    Write-Host "OpenSSL not found. Using Python cryptography library..." -ForegroundColor Yellow
    # The certs are generated by the Python script
    & python "$ScriptDir\..\..\scripts\generate_mqtt_certs.py"
    exit $LASTEXITCODE
}

Write-Host "OpenSSL found. Generating certificates..." -ForegroundColor Green

# Create output directories
New-Item -ItemType Directory -Force -Path $DockerCertsDir | Out-Null
New-Item -ItemType Directory -Force -Path $NativeCertsDir | Out-Null

# Config for CA
$caConfig = @"
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_ca
prompt = no

[req_distinguished_name]
C = CN
ST = Beijing
L = Beijing
O = Beneh MQTT BBS
CN = Beneh MQTT CA

[v3_ca]
basicConstraints = critical, CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
"@

# Config for server cert
$serverConfig = @"
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CN
ST = Beijing
L = Beijing
O = Beneh MQTT BBS
CN = localhost

[v3_req]
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = 127.0.0.1
DNS.3 = broker
"@

# Write config files
$caConfigFile = Join-Path $DockerCertsDir "ca_config.cnf"
$serverConfigFile = Join-Path $DockerCertsDir "server_config.cnf"
Set-Content -Path $caConfigFile -Value $caConfig -Encoding ASCII
Set-Content -Path $serverConfigFile -Value $serverConfig -Encoding ASCII

# Step 1: Generate CA key and cert
& $openssl genrsa -out "$DockerCertsDir\ca.key" 4096
& $openssl req -x509 -new -nodes -key "$DockerCertsDir\ca.key" -sha256 -days 3650 `
    -out "$DockerCertsDir\ca.crt" -config $caConfigFile

# Step 2: Generate server key and CSR
& $openssl genrsa -out "$DockerCertsDir\server.key" 2048
& $openssl req -new -key "$DockerCertsDir\server.key" `
    -out "$DockerCertsDir\server.csr" -config $serverConfigFile

# Step 3: Sign server cert with CA
& $openssl x509 -req -in "$DockerCertsDir\server.csr" `
    -CA "$DockerCertsDir\ca.crt" -CAkey "$DockerCertsDir\ca.key" -CAcreateserial `
    -out "$DockerCertsDir\server.crt" -days 365 -sha256 `
    -extfile $serverConfigFile -extensions v3_req

# Step 4: Copy to native Mosquitto directory
Copy-Item "$DockerCertsDir\ca.crt" "$NativeCertsDir\ca.crt" -Force
Copy-Item "$DockerCertsDir\server.key" "$NativeCertsDir\server.key" -Force
Copy-Item "$DockerCertsDir\server.crt" "$NativeCertsDir\server.crt" -Force

# Cleanup
Remove-Item $caConfigFile, $serverConfigFile, "$DockerCertsDir\server.csr", "$DockerCertsDir\ca.srl" -ErrorAction SilentlyContinue

Write-Host "Certificates generated successfully!" -ForegroundColor Green
Write-Host "  CA:       $DockerCertsDir\ca.crt" -ForegroundColor Cyan
Write-Host "  Server:   $DockerCertsDir\server.crt" -ForegroundColor Cyan
Write-Host "  Key:      $DockerCertsDir\server.key" -ForegroundColor Cyan
