#!/usr/bin/env python3
"""tools/html_slides.py — 从LLM分析结果生成slide分页HTML (v2 流式布局)"""
import json, pathlib, sys

BASE = pathlib.Path(__file__).resolve().parent.parent

def generate(analysis, stem):
    c1 = analysis.get("colors",{}).get("primary","#4369e8")
    c2 = analysis.get("colors",{}).get("secondary","#2ecca8")
    c3 = analysis.get("colors",{}).get("accent","#f39c12")
    cr = c1[1:3]+","+c1[3:5]+","+c1[5:7]
    title = analysis.get("title",stem)
    subtitle = analysis.get("subtitle","")
    
    css = f"""*{{margin:0;padding:0;box-sizing:border-box;font-family:'Microsoft YaHei','PingFang SC',sans-serif}}
body{{counter-reset:slide;background:linear-gradient(135deg,#0f0f1a,#1a1a2e,#16213e,#0f3460);color:#fff}}
.slide{{min-height:100vh;padding:40px 60px;page-break-after:always;counter-increment:slide}}
.slide>{{'':''}}/* ensure vertical flow */
.sh{{padding-bottom:16px;margin-bottom:20px;border-bottom:1px solid rgba(255,255,255,0.08)}}
.sh h2{{font-size:28px;color:{c1}}}
.kp{{font-size:15px;color:#8899bb;margin-bottom:20px;line-height:1.6}}
.mr{{display:flex;flex-wrap:wrap;gap:12px;margin-top:25px;justify-content:center}}
.mc{{background:rgba(255,255,255,0.04);border-radius:12px;padding:18px 24px;text-align:center;border:1px solid rgba(255,255,255,0.06)}}
.mc .mv{{font-size:30px;font-weight:800;background:linear-gradient(135deg,{c1},{c2});-webkit-background-clip:text;-webkit-text-fill-color:transparent}}
.mc .ml{{font-size:12px;color:#8899bb;margin-top:4px}}
.cr>{{'':''}}/* cards flow vertically */
.card{{background:rgba(255,255,255,0.03);border-radius:10px;padding:16px 20px;margin-bottom:12px;border-left:4px solid {c3}}}
.card h3{{font-size:15px;font-weight:600;margin-bottom:8px;color:#fff}}
.card li{{font-size:13px;color:#ccc;padding:2px 0 2px 14px;list-style:none;position:relative}}
.card li:before{{content:'\\2022';color:{c2};position:absolute;left:0}}
.cb{{width:100%;height:420px;margin:10px 0}}
.nav{{position:fixed;bottom:25px;left:50%;transform:translateX(-50%);display:flex;gap:8px;z-index:100}}
.nav a{{width:10px;height:10px;border-radius:50%;background:#445;cursor:pointer}}
.nav a:hover,.nav a.active{{background:{c1};transform:scale(1.3)}}
@media print{{.slide{{page-break-after:always;min-height:100vh}}}}
"""
    
    slides = []
    charts_js = []
    
    metrics = analysis.get("metrics",[])
    mc = "".join(f'<div class="mc"><div class="mv">{m["value"]}</div><div class="ml">{m["label"]}</div></div>' for m in metrics[:6])
    slides.append(f'<div class="slide" style="display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center"><h1 style="font-size:44px;font-weight:700;background:linear-gradient(90deg,{c1},{c2},#e2a8ff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:12px">{title}</h1><p style="font-size:16px;color:#8899bb;margin-bottom:18px">{subtitle}</p><span style="padding:6px 20px;border-radius:16px;background:rgba({cr},0.15);border:1px solid rgba({cr},0.25);color:{c1};font-size:13px;margin-bottom:20px">LLM+ECharts Presentation</span><div class="mr">{mc}</div></div>')
    
    for i,c in enumerate(analysis.get("charts",[])):
        cid = c.get("id","ch"+str(i))
        opt = json.dumps(c.get("option",{}))
        slides.append(f'<div class="slide"><div class="sh"><h2>{c.get("title","Chart")}</h2></div><div id="{cid}" class="cb"></div></div>')
        charts_js.append(f'var c{i}=echarts.init(document.getElementById("{cid}"));c{i}.setOption({opt});window.addEventListener("resize",function(){{c{i}.resize()}});')
    
    for s in analysis.get("sections",[]):
        cards = "".join(f'<div class="card"><h3>{c.get("title","")}</h3>{"".join(f"<li>{it}</li>" for it in c.get("items",[]))}</div>' for c in s.get("cards",[]))
        slides.append(f'<div class="slide"><div class="sh"><h2>{s.get("title","")}</h2></div><p class="kp">{s.get("key_point","")}</p><div class="cr">{cards}</div></div>')
    
    slides.append(f'<div class="slide" style="display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center"><h1 style="font-size:36px;color:#fff">Thank You</h1><p style="color:#8899bb;font-size:14px;margin-top:10px">Generated by GA Pipeline v2 - pptVisualDesign + presentationStorytelling</p></div>')
    
    nav = "".join(f'<a href="#s{i}" onclick="document.getElementById(\'s{i}\').scrollIntoView({{behavior:\'smooth\'}});document.querySelectorAll(\'.nav a\').forEach(function(a){{a.className=\'\'}});this.className=\'active\'"></a>' for i in range(1, len(slides)+1))

    html = f'''<!DOCTYPE html><html lang="zh-CN"><head>
<meta charset="utf-8"><title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>
<style>{css}</style></head><body>
{"".join(s for s in slides)}
<div class="nav">{nav}</div>
<script>{"".join(charts_js)}
document.addEventListener("scroll",function(){{var s=Math.round(window.scrollY/window.innerHeight);document.querySelectorAll(".nav a").forEach(function(a,i){{a.className=i===s?"active":""}})}});
</script></body></html>'''
    return html


if __name__ == "__main__":
    import json, sys
    data = json.loads(open(sys.argv[1]).read())
    html = generate(data, sys.argv[2] if len(sys.argv)>2 else "slide")
    out = sys.argv[3] if len(sys.argv)>3 else sys.stdout
    if out != sys.stdout:
        open(out,"w",encoding="utf-8").write(html)
        print(f"[OK] HTML: {out}")
    else:
        print(html)
